-- Initiales Schema für die generische Entitäts-Tabelle.
-- Kompatibel mit PostgreSQL und H2 (MODE=PostgreSQL).
CREATE TABLE entity (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pk    VARCHAR(36)  NOT NULL DEFAULT RANDOM_UUID(),
    date  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    type  VARCHAR(255),
    data  JSON,
    CONSTRAINT uq_entity_pk UNIQUE (pk)
);

